artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source: C:\\Users\\paago\\Downloads\\Chicken_Fecal.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
  source_csv: artifacts\\data_ingestion\\Fecal_data.csv


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5
  class_indices_path: artifacts/prepare_base_model/class_indices.json
