data_ingestion:

artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source: C:\\Users\\paago\\Downloads\\Chicken_Fecal.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
